### ISSUE TITLE
Implement way for display stickers/emoji without wasm

### ISSUE THREAD

**Issue by Azq2** [morethanwords/tweb#114]
**Is your feature request related to a problem? Please describe.**
I tried to use this client on localhost with CSP headers, but wasm not works without 'unsafe-eval'
App works, but any big emoji or animated stickers not shown.

```
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
    at abort (rlottie-wasm.js:1:13126)
    at rlottie-wasm.js:1:14788
```

My CSP headers:
```
add_header Content-Security-Policy "script-src 'self'; object-src 'self';";
```

// CSP with unsafe-eval is useless :) 

**Describe the solution you'd like**
It would be cool if we implement fallback for case, when wasm rlottie not works/not loaded.

**Describe alternatives you've considered**
In [[webz.telegram,org]()](https://github.com/Ajaxy/telegram-tt) stickers works with CSP (But this client has 10 times more bugs. Not usable at all).

**Additional context**
![image](https://user-images.githubusercontent.com/5139482/162573565-7e3d82cd-2d21-4d19-87dd-0fe235f133f5.png)
![image](https://user-images.githubusercontent.com/5139482/162573568-e2615782-f6a8-4070-b38e-905f79125754.png)
![image](https://user-images.githubusercontent.com/5139482/162573572-591ae063-5b37-4df2-93ca-12da2aad9a0c.png)

**Comment by carlosala** [comment]
@morethanwords this is still happening, how could we solve this?
