### ISSUE TITLE
[BUG] npm run build error

### ISSUE THREAD

**Issue by zxndev** [morethanwords/tweb#203]
PS D:\Projects\Telegram\tweb> npm run build

> tweb@1.0.0 build
> npm run generate-changelog && webpack --config webpack.prod.js

> tweb@1.0.0 generate-changelog
> node ./src/scripts/generate_changelog.js

node:internal/fs/utils:347
    throw err;
    ^

.md'r: ENOENT: no such file or directory, open './public/changelogs/en_0.8.6
    at Object.openSync (node:fs:600:3)
    at Object.writeFileSync (node:fs:2221:35)
    at D:\Projects\Telegram\tweb\src\scripts\generate_changelog.js:41:8
    at Array.forEach (<anonymous>)
    at processChangelog (D:\Projects\Telegram\tweb\src\scripts\generate_changelog.js:24:12)
    at D:\Projects\Telegram\tweb\src\scripts\generate_changelog.js:47:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\Projects\Telegram\tweb\src\scripts\generate_changelog.js:45:11)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './public/changelogs/en_0.8.6\r.md'
}

Node.js v18.14.0

**Comment by morethanwords** [comment]
Make sure you have `public` directory and, as well as `changelogs` inside of it.

**Comment by DittmerOk** [comment]
![image](https://github.com/morethanwords/tweb/assets/56869986/77d900ce-4bfe-4378-8317-b062d67e500d)
I have public/changelogs. But I can not have en_0.8.6\r.md. What can I do?
