### ISSUE TITLE
[vite:build-import-analysis] Cannot read properties of undefined (reading 'importedCss')[BUG]

### ISSUE THREAD

**Issue by yunjieye** [morethanwords/tweb#279]
run build will report bug
error during build:
TypeError: Cannot read properties of undefined (reading 'importedCss')
    at addDeps (file:///D:/Users/jay77/WebstormProjects/tweb-master/node_modules/.pnpm/vite@4.5.1_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-68d1a114.js:46875:60)
    at Object.generateBundle (file:///D:/Users/jay77/WebstormProjects/tweb-master/node_modules/.pnpm/vite@4.5.1_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-68d1a114.js:46895:33)

**Comment by morethanwords** [comment]
See [this](https://github.com/morethanwords/tweb/issues/269) issue.
